// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.eshop25.Infrastructure.Database;

#nullable disable

namespace UTB.eshop25.Infrastructure.Migrations
{
    [DbContext(typeof(EshopDbContext))]
    [Migration("20251011090622_mysql_1.0.1_seeding")]
    partial class mysql_101_seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTB.eshop25.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSrc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nejlepší chleba na kontinentu",
                            ImageSrc = "/img/products/product-1.png",
                            Name = "Chleba",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nejlepší rohlík v galaxii",
                            ImageSrc = "/img/products/product-2.png",
                            Name = "Rohlík",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nejlepší bageta ve vesmíru",
                            ImageSrc = "/img/products/product-3.png",
                            Name = "Bageta",
                            Price = 25.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
